[project]
name = "vidianiv_jetson_service"
description = "VIDIANIV Project: Jetson Nano Service."
version = "0.0.1"
authors = [
    { name = "Victor Smirnov", email = "vityaman.dev@yandex.ru" },
]
dependencies = [
    "jetson-inference", # Check https://github.com/dusty-nv/jetson-inference
    "jetson-util",      # Docker container.
]

[tool.mypy]
python_version = "3.7"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
